version: "3.7"
services:

#Laravel App
  app:
    build:
      args:
        user: yugonorom
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: omdod_lara_app
    container_name: omdod-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - omdod-network
    
 #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: omdod-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - omdod-network

#Mysql Service
  db:
    image: mysql:5.7.22
    container_name: omdod-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - omdod-network

# redis
  redis:
      container_name: omdod-redis
      image: redis:latest
      networks: 
          - omdod-network
      
networks:
  omdod-network:
    driver: bridge